services:
  - type: web
    name: pairo-web
    env: docker
    plan: free
    autoDeploy: true

    envVars:
      - key: DEBUG
        value: "False"

      - key: SECRET_KEY
        generateValue: true

      - key: DB_HOST
        fromDatabase:
          name: pairo-db
          property: host

      - key: DB_NAME
        fromDatabase:
          name: pairo-db
          property: database

      - key: DB_USER
        fromDatabase:
          name: pairo-db
          property: user

      - key: DB_PASSWORD
        fromDatabase:
          name: pairo-db
          property: password

      # âœ… POSTGRES PORT
      - key: DB_PORT
        value: "5432"

databases:
  - name: pairo-db
    plan: free
